@startuml
left to right direction
actor "Usuário" as User
rectangle "Sistema de Gestão" {
  User -- (Cadastrar Projeto)
  User -- (Editar Projeto)
  User -- (Excluir Projeto)
  User -- (Listar Projetos)
  User -- (Ver Detalhes do Projeto)
}
@enduml